### ISSUE TITLE
404 status code does not give a failure

### ISSUE THREAD

**Issue by thierrybucco** [awkward/Ocarina#10]
In OcarinaManager in taskDidComplete receiving a 404 statusCode will not execute failure block.

if let response = response, response.statusCode < 200 && response.statusCode >= 300 {

it should be response.statusCode < 200 **||** response.statusCode >= 300

Also it would be nice to expose HTTPURLResponse in error.UserInfo

**Comment by renssies** [comment]
That was a good catch, I've approved and merged your PR: https://github.com/awkward/Ocarina/pull/11

**Comment by thierrybucco** [comment]
Thanks!
