### ISSUE TITLE
Unable to parse YouTube link

### ISSUE THREAD

**Issue by thierrybucco** [awkward/Ocarina#16]
Ocarina is unable to parse this YouTube link: 

https://www.youtube.com/watch?v=v1wfQPGXhVA

This is because og:description is in body tag instead of head.

Correct Xpath query should be: "/html/body/meta[(@property|@name)=\"og:description\"]/@content"

What do you suggest for fixing it?

@davidvanleeuwen @samuelbeek @renssies @AvdLee @daveyheuser 

Thanks!

**Comment by thierrybucco** [comment]
Fixed it. Will push.

**Comment by renssies** [comment]
I've approved your pull request and merged it. I'm planning to make some additional changes but something is wrong with the rights for me. After that, I will make a release on GitHub as well :)
